### ISSUE TITLE
share your paper--HPCA 2021

### ISSUE THREAD

**Issue by wxbbuaa2011** [VeriGOOD-ML/public#4]
I'm sorry that I didn't find your article in the HCPA2021 meeting. Could you share it with me?

**Comment by skinzer** [comment]
Hi,

Of course! Please see the paper here:

[2021-hpca-polymath.pdf](https://github.com/VeriGOOD-ML/public/files/6386176/2021-hpca-polymath.pdf)

**Comment by wxbbuaa2011** [comment]
Thanks. This is a great work again. I like it very much.

**Comment by skinzer** [comment]
Thank you, we really appreciate it!
