### ISSUE TITLE
Getting error when running run_benchmark.py from genesys

### ISSUE THREAD

**Issue by neushaj** [VeriGOOD-ML/public#7]
I was trying to run resnet18 benchmark from Genesys and I got multiple errors as follows:
![image](https://user-images.githubusercontent.com/77736443/187090186-074099b8-6f41-4330-a0a1-2d49fa7be47f.png)

I'm sure I have installed all of the requirements packages and Polymath, but it seems there is a problem with importing local files and some files (especially from "codelts" folder) are missing.
The only thing I've modified was copying "codelts" and "Polymath" folders beside run_benchmark.py in genesys/benchmarks/ folder, because there was an error saying that it cannot find these two.

**Comment by InputBlackBoxOutput** [comment]
Hi @neushaj, 

I am also running into a similar error while trying to run the GeneSys tool. Were you able to fix the issue?

![image](https://user-images.githubusercontent.com/53337979/213347033-41534d59-381c-43b4-8371-9ba7e16b97d8.png)


Thanks!

**Comment by InputBlackBoxOutput** [comment]
I figured it out. We were using the [polymath](https://pypi.org/project/polymath/) from PyPI. Use the polymath module from https://github.com/he-actlab/polymath

**Comment by sapatnekar** [comment]
Polymath has been updated
