### ISSUE TITLE
Documentation needs update

### ISSUE THREAD

**Issue by mayagokhale** [VeriGOOD-ML/public#8]
1. I was not able to run axiline using the documentation in the README. It would be good to explain how to install polymath from axiline since polymath appears to need its own venv separate from the axiline venv. I finally just installed native with python 3.10 and downloaded packages as needed.

2. axiline invokes mgdfg. However polymath has srdfg. I had to change those imports in multiple files.

3. the documentation in the README on the flags to axiline_compiler for -o and -op is backwards from the code. The code expects -o to be the output path and -op to be the onnx filepath.

**Comment by ziqingzeng** [comment]
Thanks for the comments. The documentation and polymath imports are updated.
