### ISSUE TITLE
Boston data set used by axiline

### ISSUE THREAD

**Issue by mayagokhale** [VeriGOOD-ML/public#9]
This dataset is deprecated. Actually it isn't even used.

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

**Comment by ziqingzeng** [comment]
This dataset was used in previous tests with decision tree generation. Thanks for the reminder, it was removed in a recent update.
